-- SPVCURR
SELECT SPRIDEN_PIDM,
       SPRIDEN_ID,
       DECODE (SPRIDEN_ENTITY_IND,'C', SPRIDEN_LAST_NAME, SPRIDEN_LAST_NAME || ', ' || SPRIDEN_FIRST_NAME || ' ' || SPRIDEN_MI),
       SPRIDEN_LAST_NAME,
       SPRIDEN_FIRST_NAME,
       SPRIDEN_ACTIVITY_DATE
FROM SPRIDEN,
     SPBPERS
WHERE SPRIDEN_PIDM = SPBPERS_PIDM
  AND SPRIDEN_CHANGE_IND IS NULL
  AND SPBPERS_DEAD_IND IS NULL